version: '2.4'

services:
  db:
    image: postgres
    mem_limit: 50M
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=jikanganai
      - POSTGRES_USER=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  express:
    image: jikan-ga-nai-server
#    build: .
    mem_limit: 100M
    ports:
      - "9998:9998"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOSTNAME=db
      - SYNC_DB=false
      # image is set to Australia/Melbourne by default
#      - TZ=Australia/Sydney
    depends_on:
      - db

  ember:
    image: jikan-ga-nai-client
    #    build: ../jikan-ga-nai-client/docker/
    mem_limit: 50M
    ports:
      - "9997:80"
    environment:
      - GRAPHQL_HOST=192.168.1.54
      - GRAPHQL_PORT=9998
      - START_HOUR_OFFSET=0
    depends_on:
      - express

volumes:
  postgres:
