export const CREATED_TRACKEDDAY = "CREATED_TRACKEDDAY";
export const CREATED_TRACKEDTASK = "CREATED_TRACKEDTASK";
export const CREATED_CHARGECODE = "CREATED_CHARGECODE";
export const CREATED_TIMEBLOCK = "CREATED_TIMEBLOCK";

export const UDPATED_CHARGECODE = "UPDATED_CHARGECODE";
export const UPDATED_TRACKEDTASK = "UPDATED_TRACKEDTASK";
export const UPDATED_TIMESHEET = "UPDATED_TIMESHEET";

export const DELETED_TIMEBLOCK = "DELETED_TIMEBLOCK";
export const DELETED_TRACKEDTASK = "DELETED_TRACKEDTASK";
export const DELETED_TRACKEDDAY = "DELETED_TRACKEDDAY";
